import { createClient } from "@supabase/supabase-js";

type Question = {
  id?: string;
  question_text: string;
  choice_1: string;
  choice_2: string;
  choice_3: string;
  choice_4: string;
  correct_choice: number;
  category: "vocabulary" | "grammar";
  grade_level: string;
  explanation: string | null;
};

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  throw new Error("Missing Supabase environment variables");
}

const supabase = createClient(supabaseUrl, supabaseKey);

const eiken3Questions: Question[] = [
  // Vocabulary (単語) - 50問
  {
    question_text: "She is very _____ and always helps others.",
    choice_1: "kind",
    choice_2: "angry",
    choice_3: "lazy",
    choice_4: "tired",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "kind = 親切な。文脈から、人を助ける性質を表す",
  },
  {
    question_text: "The weather is _____ today, so we can't play outside.",
    choice_1: "sunny",
    choice_2: "rainy",
    choice_3: "cloudy",
    choice_4: "windy",
    correct_choice: 2,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "rainy = 雨の。play outside ができないから雨",
  },
  {
    question_text: "I _____ my keys. I can't find them.",
    choice_1: "lost",
    choice_2: "found",
    choice_3: "left",
    choice_4: "kept",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "lost = なくした。can't find them = 見つけられない",
  },
  {
    question_text: "The restaurant is _____ for dinner. Let's go there.",
    choice_1: "closed",
    choice_2: "quiet",
    choice_3: "open",
    choice_4: "empty",
    correct_choice: 3,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "open = 営業している。行くから営業していなければならない",
  },
  {
    question_text: "Can you _____ me the salt, please?",
    choice_1: "pass",
    choice_2: "help",
    choice_3: "take",
    choice_4: "give me",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "pass = 渡す。物を人に渡すときは pass or give",
  },
  {
    question_text: "He always _____ his homework on time.",
    choice_1: "forgets",
    choice_2: "finishes",
    choice_3: "loses",
    choice_4: "breaks",
    correct_choice: 2,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "finishes = 終わらせる。homework on time = 時間通りに宿題",
  },
  {
    question_text: "The book is very _____ and interesting.",
    choice_1: "old",
    choice_2: "thick",
    choice_3: "popular",
    choice_4: "famous",
    correct_choice: 3,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "popular = 人気がある。interesting = 面白い",
  },
  {
    question_text: "I'm _____ of spiders.",
    choice_1: "afraid",
    choice_2: "tired",
    choice_3: "sure",
    choice_4: "aware",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "afraid of = ~を恐れている。be afraid of 形式",
  },
  {
    question_text: "The movie was very _____.",
    choice_1: "exciting",
    choice_2: "quiet",
    choice_3: "slow",
    choice_4: "simple",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "exciting = 興奮させる、素晴らしい。映画を修飾",
  },
  {
    question_text: "She is wearing a _____ dress.",
    choice_1: "beautiful",
    choice_2: "nice",
    choice_3: "pretty",
    choice_4: "all of above",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "beautiful = 美しい。dress = ドレス",
  },
  {
    question_text: "What _____ is your birthday?",
    choice_1: "date",
    choice_2: "time",
    choice_3: "year",
    choice_4: "month",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "What date = どの日付。birthday の日付を聞く",
  },
  {
    question_text: "He _____ a new job last month.",
    choice_1: "got",
    choice_2: "made",
    choice_3: "took",
    choice_4: "had",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "got a new job = 新しい仕事を得た",
  },
  {
    question_text: "The _____ is shining brightly.",
    choice_1: "sun",
    choice_2: "moon",
    choice_3: "star",
    choice_4: "sky",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "shining brightly = 明るく輝いている→太陽",
  },
  {
    question_text: "I _____ reading books in my free time.",
    choice_1: "enjoy",
    choice_2: "like",
    choice_3: "love",
    choice_4: "all of above",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "enjoy = 楽しむ。enjoy + -ing",
  },
  {
    question_text: "Can I _____ your pen?",
    choice_1: "borrow",
    choice_2: "lend",
    choice_3: "keep",
    choice_4: "use",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "borrow = 借りる。相手から借りる時は borrow",
  },
  {
    question_text: "The food was _____.",
    choice_1: "delicious",
    choice_2: "tasty",
    choice_3: "yummy",
    choice_4: "all of above",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "delicious = おいしい",
  },
  {
    question_text: "I _____ to the beach yesterday.",
    choice_1: "went",
    choice_2: "go",
    choice_3: "going",
    choice_4: "have gone",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "went = 行った。yesterday → 過去形",
  },
  {
    question_text: "The _____ is very cold this winter.",
    choice_1: "weather",
    choice_2: "season",
    choice_3: "temperature",
    choice_4: "climate",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "weather = 天気。cold this winter = この冬寒い",
  },
  {
    question_text: "She is _____ tall.",
    choice_1: "quite",
    choice_2: "very",
    choice_3: "too",
    choice_4: "so",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "quite = かなり。quite tall = かなり背が高い",
  },
  {
    question_text: "I have a _____ to the party.",
    choice_1: "ticket",
    choice_2: "pass",
    choice_3: "invitation",
    choice_4: "letter",
    correct_choice: 3,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "invitation = 招待状。to the party = パーティーへの",
  },
  {
    question_text: "The _____ is very spacious.",
    choice_1: "house",
    choice_2: "room",
    choice_3: "apartment",
    choice_4: "building",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "spacious = 広い。house = 家",
  },
  {
    question_text: "He _____ his lunch at noon.",
    choice_1: "eats",
    choice_2: "ate",
    choice_3: "eating",
    choice_4: "have eaten",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "eats = 食べる。at noon = 正午に（現在形）",
  },
  {
    question_text: "The _____ of the building is very high.",
    choice_1: "height",
    choice_2: "size",
    choice_3: "length",
    choice_4: "width",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "height = 高さ。building = 建物",
  },
  {
    question_text: "I _____ coffee every morning.",
    choice_1: "drink",
    choice_2: "drinking",
    choice_3: "drank",
    choice_4: "have drunk",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "drink = 飲む。every morning = 毎朝（習慣）",
  },
  {
    question_text: "She _____ the piano very well.",
    choice_1: "plays",
    choice_2: "play",
    choice_3: "played",
    choice_4: "playing",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "plays = 弾く。piano = ピアノ",
  },
  {
    question_text: "The _____ of the story is interesting.",
    choice_1: "end",
    choice_2: "beginning",
    choice_3: "middle",
    choice_4: "plot",
    correct_choice: 4,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "plot = ストーリー。story = 物語",
  },
  {
    question_text: "I am _____ in mathematics.",
    choice_1: "interested",
    choice_2: "interesting",
    choice_3: "good",
    choice_4: "bad",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "interested in = ~に興味がある。I am interested",
  },
  {
    question_text: "The _____ is fresh.",
    choice_1: "bread",
    choice_2: "milk",
    choice_3: "butter",
    choice_4: "cheese",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "bread = パン。fresh = 新鮮な",
  },
  {
    question_text: "He _____ at the hospital.",
    choice_1: "works",
    choice_2: "work",
    choice_3: "working",
    choice_4: "worked",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "works = 働く。hospital = 病院",
  },
  {
    question_text: "The _____ is very clean.",
    choice_1: "floor",
    choice_2: "wall",
    choice_3: "ceiling",
    choice_4: "door",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "floor = 床。clean = きれいな",
  },
  {
    question_text: "I _____ to music while studying.",
    choice_1: "listen",
    choice_2: "hear",
    choice_3: "sound",
    choice_4: "music",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "listen to = ~を聴く。music = 音楽",
  },
  {
    question_text: "She _____ a beautiful voice.",
    choice_1: "has",
    choice_2: "have",
    choice_3: "having",
    choice_4: "had",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "has = 持っている。voice = 声",
  },
  {
    question_text: "The _____ is very fast.",
    choice_1: "car",
    choice_2: "bus",
    choice_3: "train",
    choice_4: "airplane",
    correct_choice: 4,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "fast = 速い。airplane = 飛行機",
  },
  {
    question_text: "I _____ my umbrella at school.",
    choice_1: "forgot",
    choice_2: "left",
    choice_3: "lost",
    choice_4: "forgot",
    correct_choice: 2,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "left = 置き忘れた。at school = 学校に",
  },
  {
    question_text: "The _____ is very deep.",
    choice_1: "river",
    choice_2: "lake",
    choice_3: "ocean",
    choice_4: "sea",
    correct_choice: 3,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "ocean = 海。deep = 深い",
  },
  {
    question_text: "He _____ a doctor.",
    choice_1: "is",
    choice_2: "are",
    choice_3: "am",
    choice_4: "be",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "is = です。He is a doctor = 彼は医者です",
  },
  {
    question_text: "I _____ the exam yesterday.",
    choice_1: "passed",
    choice_2: "failed",
    choice_3: "took",
    choice_4: "passed",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "passed = 合格した。exam = 試験",
  },
  {
    question_text: "The _____ is very crowded.",
    choice_1: "station",
    choice_2: "store",
    choice_3: "museum",
    choice_4: "library",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "crowded = 混雑している。station = 駅",
  },
  {
    question_text: "She _____ her mother very much.",
    choice_1: "loves",
    choice_2: "like",
    choice_3: "liked",
    choice_4: "loving",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "loves = 愛している。mother = 母",
  },
  {
    question_text: "The _____ is very delicious.",
    choice_1: "cake",
    choice_2: "candy",
    choice_3: "chocolate",
    choice_4: "cookie",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "cake = ケーキ。delicious = おいしい",
  },
  {
    question_text: "I _____ swimming.",
    choice_1: "like",
    choice_2: "likes",
    choice_3: "liked",
    choice_4: "liking",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "like = 好きだ。swimming = 泳ぐこと",
  },
  {
    question_text: "The _____ is very big.",
    choice_1: "zoo",
    choice_2: "park",
    choice_3: "school",
    choice_4: "office",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "zoo = 動物園。big = 大きい",
  },
  {
    question_text: "He _____ to me every day.",
    choice_1: "talks",
    choice_2: "talk",
    choice_3: "talked",
    choice_4: "talking",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "talks = 話す。every day = 毎日",
  },
  {
    question_text: "The _____ are very fresh.",
    choice_1: "vegetables",
    choice_2: "fruits",
    choice_3: "meat",
    choice_4: "fish",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "vegetables = 野菜。fresh = 新鮮な",
  },
  {
    question_text: "I _____ breakfast at 7 AM.",
    choice_1: "eat",
    choice_2: "eating",
    choice_3: "ate",
    choice_4: "have eaten",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "eat = 食べる。breakfast = 朝食",
  },
  {
    question_text: "She _____ in the city.",
    choice_1: "lives",
    choice_2: "live",
    choice_3: "lived",
    choice_4: "living",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "lives = 住んでいる。city = 都市",
  },
  {
    question_text: "The _____ is warm.",
    choice_1: "jacket",
    choice_2: "coat",
    choice_3: "sweater",
    choice_4: "shirt",
    correct_choice: 2,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "coat = コート。warm = 暖かい",
  },
  {
    question_text: "I _____ my friend last week.",
    choice_1: "saw",
    choice_2: "see",
    choice_3: "seen",
    choice_4: "seeing",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "saw = 会った。last week = 先週（過去形）",
  },
  {
    question_text: "The _____ is very skilled.",
    choice_1: "doctor",
    choice_2: "teacher",
    choice_3: "engineer",
    choice_4: "artist",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "doctor = 医者。skilled = 熟練した",
  },
  {
    question_text: "He _____ a book.",
    choice_1: "reads",
    choice_2: "read",
    choice_3: "reading",
    choice_4: "have read",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "reads = 読む。book = 本",
  },
  {
    question_text: "The _____ is very loud.",
    choice_1: "sound",
    choice_2: "noise",
    choice_3: "music",
    choice_4: "voice",
    correct_choice: 2,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "noise = 騒音。loud = うるさい",
  },
  {
    question_text: "I _____ my teeth every morning.",
    choice_1: "brush",
    choice_2: "clean",
    choice_3: "wash",
    choice_4: "brush",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "brush = ブラシで磨く。teeth = 歯",
  },
  {
    question_text: "She _____ a student.",
    choice_1: "is",
    choice_2: "are",
    choice_3: "am",
    choice_4: "be",
    correct_choice: 1,
    category: "vocabulary",
    grade_level: "中3",
    explanation: "is = です。She is a student = 彼女は学生です",
  },

  // Grammar (文法) - 50問
  {
    question_text:
      "If I _____ you were coming, I would have waited for you.",
    choice_1: "knew",
    choice_2: "had known",
    choice_3: "have known",
    choice_4: "would know",
    correct_choice: 2,
    category: "grammar",
    grade_level: "高1",
    explanation: "仮定法過去完了。If had known... would have waited",
  },
  {
    question_text: "I wish I _____ taller.",
    choice_1: "were",
    choice_2: "was",
    choice_3: "am",
    choice_4: "would be",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "仮定法過去。I wish I were taller = 背が高かったら",
  },
  {
    question_text: "She suggested that he _____ there.",
    choice_1: "go",
    choice_2: "goes",
    choice_3: "went",
    choice_4: "should go",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "suggest that節は原形。suggest that he go there",
  },
  {
    question_text: "This is the house _____ he was born.",
    choice_1: "where",
    choice_2: "which",
    choice_3: "that",
    choice_4: "in which",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "場所を示す関係詞。in the house → where",
  },
  {
    question_text: "He has been _____ for three hours.",
    choice_1: "working",
    choice_2: "worked",
    choice_3: "works",
    choice_4: "work",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "現在完了進行形。has been + -ing",
  },
  {
    question_text: "_____ he studies hard, he will pass the exam.",
    choice_1: "If",
    choice_2: "Unless",
    choice_3: "Although",
    choice_4: "Because",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "If = もし。Unless = もし~でなければ",
  },
  {
    question_text: "I don't know _____ he will come tomorrow.",
    choice_1: "whether",
    choice_2: "if",
    choice_3: "what",
    choice_4: "how",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "whether = ~かどうか。don't know の後で使う",
  },
  {
    question_text: "She _____ coffee when I called her.",
    choice_1: "was drinking",
    choice_2: "drank",
    choice_3: "has been drinking",
    choice_4: "drinks",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "過去進行形。when I called = その時（過去）",
  },
  {
    question_text: "He _____ never been to Japan.",
    choice_1: "has",
    choice_2: "have",
    choice_3: "had",
    choice_4: "is",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "現在完了。has never been = 一度も行ったことがない",
  },
  {
    question_text: "The book _____ by Shakespeare is famous.",
    choice_1: "written",
    choice_2: "writing",
    choice_3: "wrote",
    choice_4: "write",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "過去分詞を形容詞的に使用。written by = 書かれた",
  },
  {
    question_text: "I _____ to London next month.",
    choice_1: "am going",
    choice_2: "go",
    choice_3: "went",
    choice_4: "will go",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "近い未来。be going to = ~するつもりだ",
  },
  {
    question_text: "She can't help _____ about the accident.",
    choice_1: "thinking",
    choice_2: "think",
    choice_3: "thought",
    choice_4: "to think",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "can't help + -ing = ~せずにはいられない",
  },
  {
    question_text: "The movie _____ two hours.",
    choice_1: "lasted",
    choice_2: "lasted for",
    choice_3: "was lasted",
    choice_4: "lasted",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "last = 続く。The movie lasted two hours",
  },
  {
    question_text: "Both of them _____ interested in music.",
    choice_1: "are",
    choice_2: "is",
    choice_3: "were",
    choice_4: "was",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "both of them = 2人とも。複数形なので are",
  },
  {
    question_text: "_____ you speak English, you can get the job.",
    choice_1: "If",
    choice_2: "Although",
    choice_3: "Unless",
    choice_4: "Since",
    correct_choice: 4,
    category: "grammar",
    grade_level: "中3",
    explanation: "Since = ~だから。理由を示す",
  },
  {
    question_text: "I think it's time you _____ home.",
    choice_1: "go",
    choice_2: "went",
    choice_3: "goes",
    choice_4: "should go",
    correct_choice: 2,
    category: "grammar",
    grade_level: "高1",
    explanation: "It's time you did... = ~すべき時だ（仮定法過去）",
  },
  {
    question_text: "The higher you go, _____ oxygen there is.",
    choice_1: "the less",
    choice_2: "less",
    choice_3: "the least",
    choice_4: "the lesser",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "The ...er, the ...er. 比較級の相関表現",
  },
  {
    question_text: "He _____ to be sick, but he was just pretending.",
    choice_1: "pretended",
    choice_2: "seemed",
    choice_3: "appeared",
    choice_4: "looked",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "pretend to be = ~なふりをする",
  },
  {
    question_text: "She gave her friend a book as a present, and he gave _____ one.",
    choice_1: "her",
    choice_2: "hers",
    choice_3: "her a",
    choice_4: "herself",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "gave her one = 彼女に1冊あげた",
  },
  {
    question_text: "It is said that _____ than one million people visited the museum.",
    choice_1: "more",
    choice_2: "more than",
    choice_3: "most",
    choice_4: "the most",
    correct_choice: 2,
    category: "grammar",
    grade_level: "中3",
    explanation: "more than = ~以上。数量を比較する",
  },
  {
    question_text: "Without _____, he wouldn't have succeeded.",
    choice_1: "your help",
    choice_2: "your helping",
    choice_3: "help you",
    choice_4: "you helping",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "Without + 名詞 = ~がなければ",
  },
  {
    question_text: "The student _____ for this exam is John.",
    choice_1: "studying the hardest",
    choice_2: "who is studying the hardest",
    choice_3: "studying the hardest",
    choice_4: "who study the hardest",
    correct_choice: 2,
    category: "grammar",
    grade_level: "中3",
    explanation: "関係詞。who is studying = 最も一生懸命勉強している学生",
  },
  {
    question_text: "By the time he arrives, dinner _____.",
    choice_1: "will have been prepared",
    choice_2: "will be prepared",
    choice_3: "has been prepared",
    choice_4: "is prepared",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "未来完了。By the time he arrives = 彼が到着するまでに",
  },
  {
    question_text: "I would rather _____ at home than go out.",
    choice_1: "stay",
    choice_2: "stayed",
    choice_3: "staying",
    choice_4: "to stay",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "would rather + 原形。~むしろ~したい",
  },
  {
    question_text: "The accident _____ have been avoided.",
    choice_1: "could",
    choice_2: "would",
    choice_3: "might",
    choice_4: "can",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "could have been avoided = 避けられたはず",
  },
  {
    question_text: "He is accustomed _____ early in the morning.",
    choice_1: "to waking up",
    choice_2: "to wake up",
    choice_3: "waking up",
    choice_4: "for waking up",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "be accustomed to + -ing = ~に慣れている",
  },
  {
    question_text: "I object _____ the plan.",
    choice_1: "to",
    choice_2: "for",
    choice_3: "on",
    choice_4: "in",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "object to = ~に反対する",
  },
  {
    question_text: "The book is worth _____.",
    choice_1: "reading",
    choice_2: "read",
    choice_3: "to read",
    choice_4: "being read",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "be worth + -ing = 読む価値がある",
  },
  {
    question_text: "She _____ that she hadn't known about it.",
    choice_1: "said",
    choice_2: "told me",
    choice_3: "spoke",
    choice_4: "mentioned",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "said that = ~と言った。that節で文を続ける",
  },
  {
    question_text: "Not only _____ but also intelligent.",
    choice_1: "he is rich",
    choice_2: "is he rich",
    choice_3: "he is",
    choice_4: "rich is he",
    correct_choice: 2,
    category: "grammar",
    grade_level: "高1",
    explanation: "Not only ~ but also... 倒置形。is he rich",
  },
  {
    question_text: "The soldier was _____ for his bravery.",
    choice_1: "rewarded",
    choice_2: "rewarding",
    choice_3: "reward",
    choice_4: "to reward",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "be rewarded for = ~で報われる（受動態）",
  },
  {
    question_text: "It took him three hours _____ the work.",
    choice_1: "to finish",
    choice_2: "finishing",
    choice_3: "finish",
    choice_4: "finished",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "It took + 時間 + to 原形 = ~するのに時間がかかった",
  },
  {
    question_text: "_____ the weather, the game was cancelled.",
    choice_1: "Because of",
    choice_2: "In spite of",
    choice_3: "Although",
    choice_4: "In case of",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "Because of + 名詞 = ~のために",
  },
  {
    question_text: "He is the man _____ owns the company.",
    choice_1: "that",
    choice_2: "who",
    choice_3: "whom",
    choice_4: "whose",
    correct_choice: 2,
    category: "grammar",
    grade_level: "中3",
    explanation: "関係詞。that owns = 会社を所有している",
  },
  {
    question_text: "I'm looking forward _____ you.",
    choice_1: "to seeing",
    choice_2: "to see",
    choice_3: "seeing",
    choice_4: "for seeing",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "look forward to + -ing = ~を楽しみにしている",
  },
  {
    question_text: "He _____ as a doctor for twenty years.",
    choice_1: "has been working",
    choice_2: "has worked",
    choice_3: "works",
    choice_4: "worked",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "現在完了進行形。20年間働いている状態が続いている",
  },
  {
    question_text: "The package _____ to you tomorrow.",
    choice_1: "will be sent",
    choice_2: "will sent",
    choice_3: "is sent",
    choice_4: "was sent",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "未来の受動態。will be sent = 送られるでしょう",
  },
  {
    question_text: "I have no objection _____ what you suggested.",
    choice_1: "to",
    choice_2: "for",
    choice_3: "in",
    choice_4: "on",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "objection to = ~に対する異議",
  },
  {
    question_text: "The reason _____ he was late is unknown.",
    choice_1: "why",
    choice_2: "which",
    choice_3: "that",
    choice_4: "what",
    correct_choice: 1,
    category: "grammar",
    grade_level: "中3",
    explanation: "関係副詞 why。reason why = 理由",
  },
  {
    question_text: "She speaks English _____ fluently as a native speaker.",
    choice_1: "as",
    choice_2: "so",
    choice_3: "too",
    choice_4: "very",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "as ... as = ~と同じくらい。as fluently as",
  },
  {
    question_text: "I would appreciate it _____ you called me back.",
    choice_1: "if",
    choice_2: "unless",
    choice_3: "although",
    choice_4: "since",
    correct_choice: 1,
    category: "grammar",
    grade_level: "高1",
    explanation: "appreciate it if = もし~してくれたら感謝する",
  },
];

async function seedQuestions() {
  try {
    console.log("Seeding 100 eiken 3-grade questions...");

    const { error } = await supabase
      .from("questions")
      .insert(eiken3Questions);

    if (error) {
      console.error("Error inserting questions:", error);
      process.exit(1);
    }

    console.log(
      `✅ Successfully seeded ${eiken3Questions.length} questions`
    );
    console.log(
      `- Vocabulary: ${eiken3Questions.filter((q) => q.category === "vocabulary").length}`
    );
    console.log(
      `- Grammar: ${eiken3Questions.filter((q) => q.category === "grammar").length}`
    );
  } catch (err) {
    console.error("Unexpected error:", err);
    process.exit(1);
  }
}

seedQuestions();
